### ISSUE TITLE
Ensure that request is http message, add php 7.3 support

### ISSUE THREAD

**Issue by weierophinney** [laminas-api-tools/api-tools-http-cache#1]
---

Originally posted by @snapshotpl at https://github.com/zfcampus/zf-http-cache/pull/19

**Comment by weierophinney** [comment]
@snapshotpl any test case for the change?

---

Originally posted by @michalbundyra at https://github.com/zfcampus/zf-http-cache/pull/19#issuecomment-496677128

**Comment by froschdesign** [comment]
@snapshotpl 
Can this be closed?

**Comment by snapshotpl** [comment]
Don't need 7.3 support so close now ;)
